repos:
  # --------------------
  # Code hygiene
  # --------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: /secrets
      - id: check-added-large-files
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: /templates|/secrets
      - id: check-json
      - id: check-toml
      - id: check-shebang-scripts-are-executable

  # --------------------
  # Dockerfile lint
  # --------------------
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: ^memos/Dockerfile$

  # --------------------
  # Dockerfile security
  # --------------------
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.17.0
    hooks:
      - id: trivyconfig-docker
        files: ^memos/Dockerfile$
        args:
          - --skip-version-check
          - --severity
          - MEDIUM,HIGH,CRITICAL

  # --------------------
  # Terraform core + security
  # --------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.4
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive

      - id: terraform_validate

      - id: terraform_docs

      - id: terraform_checkov

  # --------------------
  # Terraform linting
  # --------------------
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: tflint
        files: \.tf$
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
